version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: extrums-user
      POSTGRES_PASSWORD: extrums-password
      POSTGRES_DB: extrums-db
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
